### ISSUE TITLE
Unchecking task in reading view does not trigger the marker modal

### ISSUE THREAD

**Issue by BeeFox-sys** [ebullient/obsidian-task-collector#238] opened 2023-07-09 09:12 UTC
When unchecking a task in reader view, the modal does not appear, on top of that if a task has been appended to when being checked, the modal also does not appear.

![image](https://github.com/ebullient/obsidian-task-collector/assets/42090331/79602acd-9393-41ee-9fe4-fff019421ae0)

**Comment by ebullient** [comment] 2023-07-09 13:54
1) What other plugins do you have enabled? The appearance of the modal can conflict with the tasks plugin (it depends on which was enabled last).

2) Do you have the modal enabled? And if you changed that setting, did you restart Obsidian or minimally close and reopen all notes (to force a re-render)?

<img width="789" alt="image" src="https://github.com/ebullient/obsidian-task-collector/assets/808713/759c4823-1c09-4b01-aefd-6973d3987b92">

**Comment by BeeFox-sys** [comment] 2023-07-09 14:16
oh sorry; there was a gif showing what happened, but apparently only a single frame reuploaded. the modal is enabled and appears the first time, and i don't have the tasks plugin. Poor wording on my part these are just the default checkboxes  

![task-marker-issue](https://github.com/ebullient/obsidian-task-collector/assets/42090331/8d01ab35-4149-4af1-a475-0ea010c26d1d)

**Comment by ebullient** [comment] 2023-11-30 03:03
I don't know how to reproduce this one. I use this mode fairly frequently. If/when it is flaky, it is usually due to a conflict with event handlers (closing/opening the note, or just restarting obsidian) will sometimes sort it out.

Is it still happening? (closing for now, re-open if so)

**Closed by ebullient** 2023-11-30 03:03 UTC
